# Generated by Django 2.0.3 on 2018-03-25 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('pname', 'type')},
        ),
    ]
